# Generated by Django 3.2 on 2021-04-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'countrie'},
        ),
    ]
