# Generated by Django 3.2 on 2021-04-08 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_alter_country_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='country.country'),
            preserve_default=False,
        ),
    ]
