# Generated by Django 3.2 on 2021-04-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mode', '0002_auto_20210408_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comodity',
            name='name',
            field=models.CharField(max_length=30, verbose_name='name'),
        ),
    ]
