# Generated by Django 3.2 on 2021-04-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=5, verbose_name='country code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.EmailField(max_length=254, verbose_name='country name'),
        ),
    ]
