# Generated by Django 3.2 on 2021-04-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210407_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=30, verbose_name='country name'),
        ),
    ]
